### PR TITLE
Upgrade to Cake 2.0 and Dotnet 6

### LINKED ISSUE #44: Upgrade to Cake 2.0
https://github.com/cake-contrib/cake-yarn/pull/42

Can this be upgraded to Cake 2.0? All tests pass locally, but obviously it would lose support for running on dotnet 4.8 and below only build agents. I tried it with multi targeting for dotnet core 3.1 and net6.0 and it works fine, so I can add that to the PR if needed. Now net5.0 is out of support, it doesn't seem worth targeting that framework too.

### PR DESCRIPTION
**Pull request by paulmilbank**

### CODE REVIEW

**Comment by paulmilbank** [comment]
Resolves issue https://github.com/cake-contrib/cake-yarn/issues/44

**Comment by augustoproiete** [comment]
Hey @MilovanovM can I help with getting this one merged and released?
I also would like to follow-up with a PR for adding support to Cake v3.0

**Comment by MilovanovM** [comment]
hey @augustoproiete, yes, please. I changed my entire dev stack recently, so I'm not sure I can check this out on my machine..

**Comment by augustoproiete** [comment]
@MilovanovM Awesome. I'll merge this one then, release Cake.Yarn v1.0.0 (with support for Cake v2.0.0) and then update to support Cake v3.0.0 (and release Cake.Yarn v2.0.0)

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@paulmilbank your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
